BLD: Prevent Scikit-learn 1.6.0
This version introduced the method __sklearn_tags__(),
but it currently seems broken.  Many tests run into calls for:

env\Lib\site-packages\sklearn\utils\_tags.py:396: in get_tags
    tags = estimator.__sklearn_tags__()

E AttributeError: 'super' object has no attribute '__sklearn_tags__'